### PR TITLE
Added blocks file

### PR DESCRIPTION
**Pull request by star-ranger01**
I have added a file for the **_blocks_**.

### CODE REVIEW

**Comment by SkyRanger05** [comment]
This is block file is cool like the **Rockies Mountain**..

**Comment by SkyRanger05** [comment]
I messed up there by mistake. I intended to merge but I saw the button at the bottom "Close with comment" and thought I'll give it a try. I tried but with results that failed to merge. I'll try again.

**Comment by star-ranger01** [comment]
Cool like a "cool breeze".

**Comment by SkyRanger05** [comment]
I'll let you work in this project. You have the branch "block", ok.

**Comment by star-ranger01** [comment]
Ok.

**Pull request merged**
